sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm run test -- --coverage

after_sucess:
  - docker build -t haithanh86/multi-client ./client
  - docker build -t haithanh86/multi-nginx ./nginx
  - docker build -t haithanh86/multi-server ./server
  - docker build -t haithanh86/multi-worker ./worker
  #Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push haithanh86/multi-client
  - docker push haithanh86/multi-nginx
  - docker push haithanh86/multi-server
  - docker push haithanh86/multi-worker