sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true react-test npm run test -- --coverage

after_sucess:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker