version: "3"
services:
  client:
    image: haithanh86/multi-client
    mem_limit: 128m
    hostname: client
  server:
    image: haithanh86/multi-server
    mem_limit: 128m
    hostname: api
    environments:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: haithanh86/multi-worker
    mem_limit: 128m
    hostname: worker
    environments:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: haithanh86/multi-nginx
    mem_limit: 128m
    hostname: nginx
    port:
      - "80:80"